#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'pickplace','console_scripts','destination_publisher'
__requires__ = 'pickplace'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('pickplace', 'console_scripts', 'destination_publisher')()
    )
